version: "3"
services:
  db:
    image: "postgres:15-alpine"
    container_name: "polls-db"
    restart: "always"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  postgres-data:
